import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});
import Auth from "@/store/auth";
import Chat from "@/store/chat";
import Communities from "@/store/communities";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Providers from "@/components/providers/session-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} flex flex-col scroll h-screen w-full`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          forcedTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <Auth>
              <Chat>
                <Communities>
                  <main>{children}</main>
                  <Toaster />
                </Communities>
              </Chat>
            </Auth>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
